apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - keycloak-namespace.yaml
  - rhbk-operatorgroup.yaml
  - rhbk-subscription.yaml
  - keycloak-pg-credentials-secret.yaml
  - keycloak-admin-secret.yaml
  - keycloak-pg-cluster.yaml
  - keycloak-keycloak.yaml
  - keycloak-route.yaml
  - openshift-oauth-route.yaml
