apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter
  namespace: blackbox-exporter
data:
  config.yaml: |
    modules:
      http_2xx:
        prober: http
        timeout: 10s
        http:
          preferred_ip_protocol: ip4
