apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-exporter
  namespace: blackbox-exporter
spec:
  selector:
    matchLabels:
      app: blackbox-exporter
  endpoints:
    - port: http
      path: /metrics
