apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: forgejo
  namespace: blackbox-exporter
spec:
  jobName: forgejo
  interval: 30s
  module: http_2xx
  prober:
    url: blackbox-exporter.blackbox-exporter.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - http://forgejo.forgejo.svc.cluster.local:3000/
