apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blackbox-exporter-namespace.yaml
  - blackbox-exporter-configmap.yaml
  - blackbox-exporter-deployment.yaml
  - blackbox-exporter-service.yaml
  - blackbox-exporter-servicemonitor.yaml
  - forgejo-probe.yaml
  - webapp-probe.yaml
  - webapp-prometheusrule.yaml
  - webapp-alertmanagerconfig.yaml
