apiVersion: v1
kind: Secret
metadata:
  name: forgejo-pg-credentials
  namespace: forgejo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  username: changeme
  password: changeme
