apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
resources:
  - forgejo-namespace.yaml
  - forgejo-deployment.yaml
  - forgejo-service.yaml
  - forgejo-pvc.yaml
  - forgejo-route.yaml
  - forgejo-role.yaml
  - forgejo-rolebinding.yaml
  - forgejo-serviceaccount.yaml
