apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - forgejo-namespace.yaml
  - forgejo-pg-credentials-secret.yaml
  - forgejo-admin-secret.yaml
  - forgejo-pg-cluster.yaml
  - use-scc-nonroot-v2-role.yaml
  - forgejo-nonroot-v2-rolebinding.yaml
namespace: forgejo
helmCharts:
  - name: forgejo
    namespace: forgejo
    version: 17.1.6
    releaseName: forgejo
    repo: oci://code.forgejo.org/forgejo-helm
    valuesInline:
      replicaCount: 1
      image:
        registry: code.forgejo.org
        repository: forgejo/forgejo
        tag: 15.0.8-rootless
        rootless: true
      serviceAccount:
        create: true
        name: forgejo
      persistence:
        enabled: true
        create: true
        size: 10Gi
        annotations:
          helm.sh/resource-policy: keep
          argocd.argoproj.io/sync-wave: "3"
      route:
        enabled: true
        host: forgejo.apps.demo.example.com
        tls:
          termination: edge
          insecureEdgeTerminationPolicy: Redirect
      gitea:
        admin:
          existingSecret: forgejo-admin
          passwordMode: initialOnlyNoReset
        config:
          database:
            DB_TYPE: postgres
            HOST: forgejo-pg-rw:5432
            NAME: forgejo
          server:
            ROOT_URL: https://forgejo.apps.demo.example.com/
        additionalConfigFromEnvs:
          - name: GITEA__database__USER
            valueFrom:
              secretKeyRef:
                name: forgejo-pg-credentials
                key: username
          - name: GITEA__database__PASSWD
            valueFrom:
              secretKeyRef:
                name: forgejo-pg-credentials
                key: password
      test:
        enabled: false
      deployment:
        annotations:
          argocd.argoproj.io/sync-wave: "3"
