apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - homepage-namespace.yaml
  - homepage-deployment.yaml
  - homepage-service.yaml
  - homepage-route.yaml
  - homepage-rbac.yaml
configMapGenerator:
  - name: homepage-config
    options:
      disableNameSuffixHash: false
    files:
      - config/settings.yaml
      - config/widgets.yaml
      - config/bookmarks.yaml
      - config/kubernetes.yaml
      - config/docker.yaml
      - config/proxmox.yaml
      - config/custom.css
      - config/custom.js
  - name: homepage-dashboard
    options:
      disableNameSuffixHash: false
    files:
      - dashboard.cjs
