apiVersion: v1
kind: Secret
metadata:
  name: openshell-credential-kek
  namespace: openshell
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  # Demo key-encryption key. Rotate by replacing this value before real use.
  key-encryption-key: 8TSsNqaAmPBPt4kWqEuBfsMQ+SNd0yunDxFxpxg8Kw8=
