apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshell
resources:
  - namespace.yaml
  - privileged-scc-role.yaml
  - privileged-scc-binding.yaml
  - networkpolicy.yaml
  - egress-network-policy.yaml
  - resourcequota.yaml
  - limitrange.yaml
helmCharts:
  - name: helm-chart
    namespace: openshell
    version: 0.0.116
    releaseName: openshell
    repo: oci://ghcr.io/nvidia/openshell
    valuesFile: values.yaml
patches:
  - target:
      kind: ConfigMap
      name: openshell-config
    patch: |-
      - op: add
        path: /metadata/namespace
        value: openshell
  - target:
      kind: Service
      name: openshell
    patch: |-
      - op: add
        path: /metadata/namespace
        value: openshell
  - target:
      kind: StatefulSet
      name: openshell
    patch: |-
      - op: add
        path: /metadata/namespace
        value: openshell
      - op: add
        path: /spec/template/metadata/annotations/agentic-poc.io~1config-revision
        value: opencode-sha256-1188e7b0cadb76e4
  - target:
      kind: Job
      name: openshell-certgen
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
