apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - omnigent-namespace.yaml
  - omnigent-sandboxes-namespace.yaml
  - omnigent-pg-cluster.yaml
  - omnigent-artifacts-pvc.yaml
  - omnigent-config-configmap.yaml
  - omnigent-sandbox-config-configmap.yaml
  - omnigent-server-serviceaccount.yaml
  - omnigent-runner-serviceaccount.yaml
  - molecule-tests-namespace.yaml
  - molecule-provisioner-serviceaccount.yaml
  - molecule-provisioner-rbac.yaml
  - omnigent-sandbox-manager-role.yaml
  - omnigent-sandbox-manager-rolebinding.yaml
  - omnigent-runner-nonroot-role.yaml
  - omnigent-runner-nonroot-rolebinding.yaml
  - omnigent-opencode-imagestream.yaml
  - image-build/
  - omnigent-proxy-config-configmap.yaml
  - omnigent-deployment.yaml
  - omnigent-service.yaml
  - omnigent-route.yaml
