apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - omnigent-namespace.yaml
  - omnigent-pg-cluster.yaml
  - omnigent-artifacts-pvc.yaml
  - omnigent-config-configmap.yaml
  - omnigent-sandbox-config-configmap.yaml
  - omnigent-gateway-config-configmap.yaml
  - omnigent-deployment.yaml
  - omnigent-service.yaml
  - omnigent-route.yaml
