apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  admin_password_secret: aap-admin-password
  route_tls_termination_mechanism: Edge
  ingress_type: Route
  service_type: ClusterIP
  redis_mode: standalone
  database:
    database_secret: aap-gateway-database
  metrics:
    database_secret: aap-metrics-postgres-configuration
  controller:
    postgres_configuration_secret: aap-controller-database
  hub:
    disabled: true
  eda:
    disabled: false
    database:
      database_secret: aap-eda-database
    event_stream:
      database_secret: aap-eda-event-stream-database
