apiVersion: v1
kind: Secret
metadata:
  name: aap-gateway-database
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  host: aap-pg-rw
  port: "5432"
  database: gateway
  username: changeme
  password: changeme
  sslmode: require
  type: unmanaged
