apiVersion: v1
kind: Secret
metadata:
  name: aap-metrics-read-token
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  host: aap-pg-rw
  port: "5432"
  database: controller
  username: ms_awx_readonly
  password: changeme
