apiVersion: v1
kind: Secret
metadata:
  name: aap-metrics-postgres-configuration
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  host: aap-pg-rw
  port: "5432"
  database: metricsservice
  username: metricsservice
  password: changeme
  type: unmanaged
  managed_by_aap: "true"
