apiVersion: v1
kind: Secret
metadata:
  name: aap-pg-credentials
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  username: changeme
  password: changeme
