apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: demo-aap-ee
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  runPolicy: Serial
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 1
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
      volumes:
        - name: automation-hub
          source:
            type: Secret
            secret:
              secretName: aap-ee-automation-hub
              defaultMode: 420
          mounts:
            - destinationPath: /run/build-secrets/automation-hub
  output:
    to:
      kind: ImageStreamTag
      name: demo-aap-ee:latest
