apiVersion: v1
kind: Secret
metadata:
  name: aap-metrics-database-user
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/basic-auth
stringData:
  username: metricsservice
  password: changeme

