apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: controller
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  cluster:
    name: aap-pg
  name: controller
  owner: changeme
  databaseReclaimPolicy: retain
