apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ansible-automation-platform-namespace.yaml
  - ansible-automation-platform-operatorgroup.yaml
  - ansible-automation-platform-subscription.yaml
  - aap-admin-password-secret.yaml
  - aap-pg-credentials-secret.yaml
  - aap-pg-superuser-secret.yaml
  - aap-metrics-database-secret.yaml
  - aap-metrics-read-token-secret.yaml
  - aap-pg-cluster.yaml
  - aap-gateway-database-secret.yaml
  - controller-database.yaml
  - aap-controller-database-secret.yaml
  - eda-database.yaml
  - aap-eda-database-secret.yaml
  - aap-ansibleautomationplatform.yaml
  - aap-eda-event-stream-database-secret.yaml
