apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - webapp-vms-namespace.yaml
  - webapp-services.yaml
  - webapp-login.yaml
  - webapp-route.yaml
  - aap-vm-admin-rbac.yaml
