apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sandboxed-containers-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/aiops-ansible-software-factory-demojam/openshift-gitops.git
    targetRevision: main
    path: cluster/sandboxed-containers-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-sandboxed-containers-operator
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - SkipDryRunOnMissingResource=true
