apiVersion: v1
kind: Namespace
metadata:
  name: agent-sandbox-clients
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    pod-security.kubernetes.io/enforce: restricted
