apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxWarmPool
metadata:
  name: python-kata
  namespace: agent-sandboxes
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 0
  sandboxTemplateRef:
    name: python-kata
  updateStrategy:
    type: OnReplenish
