apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sandbox-provisioner
  namespace: agent-sandboxes
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups:
      - extensions.agents.x-k8s.io
    resources:
      - sandboxclaims
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - extensions.agents.x-k8s.io
    resources:
      - sandboxwarmpools
      - sandboxtemplates
    verbs:
      - get
  - apiGroups:
      - agents.x-k8s.io
    resources:
      - sandboxes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - get
      - create
