#!/usr/bin/env bash
# Remove only catalog registrations for collections generated by this demo.
set -euo pipefail
set +x
: "${RHDH_URL:?Set the Developer Hub URL}"
: "${FORGEJO_URL:?Set the demo Forgejo URL}"
: "${BACKSTAGE_TOKEN:?Set the Backstage service credential}"

locations=$(curl -fsS --max-time 30 \
  --config <(printf 'header = "Authorization: Bearer %s"\n' "$BACKSTAGE_TOKEN") \
  "$RHDH_URL/api/catalog/locations")
mapfile -t location_ids < <(jq -r --arg prefix "$FORGEJO_URL/demo-agent/" '
  .[].data |
  select(.type == "url" and
    (.target | startswith($prefix)) and
    (.target | endswith("/src/branch/main/catalog-info.yaml"))) |
  .id
' <<< "$locations")
for location_id in "${location_ids[@]}"; do
  curl -fsS --max-time 30 -o /dev/null -X DELETE \
    --config <(printf 'header = "Authorization: Bearer %s"\n' "$BACKSTAGE_TOKEN") \
    "$RHDH_URL/api/catalog/locations/$location_id"
done
printf 'Removed %s generated collection catalog locations.\n' "${#location_ids[@]}"
