apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: forgejo-demo
spec:
  subdomain: forgejo-demo
  to:
    kind: Service
    name: forgejo-demo
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
