apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: forgejo-demo
spec:
  host: forgejo-demo.apps.cluster-dpx5t.dyn.redhatworkshops.io
  to:
    kind: Service
    name: forgejo-demo
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
