apiVersion: v1
kind: Namespace
metadata:
  name: forgejo-demo
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/part-of: forgejo-demo
    argocd.argoproj.io/managed-by: openshift-gitops
