apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: rhdh-developer-hub
  namespace: rhdh
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  database:
    enableLocalDb: false
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
    extraFiles:
      mountPath: /opt/app-root/src
      configMaps:
        - name: catalog-templates
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    extraEnvs:
      configMaps:
        - name: rhdh-demo-endpoints
      secrets:
        - name: rhdh-pg-credentials
        - name: rhdh-forgejo-credentials
    route:
      subdomain: rhdh
