apiVersion: v1
kind: Secret
metadata:
  name: rhdh-pg-credentials
  namespace: rhdh
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  username: changeme
  password: changeme
