---
schema_version: 2.0.0
name: Check Audit logs, Determine RCA, Create Issue
description: Workflow to gather logs from a host, determine RCA using AI, and create
  a new issue
triggers:
- id: alertmanagereda
  type: eda_trigger
  name: Trigger from Alertmanager
  parameters:
    webhook_path: alertmanagealert
    authorized_service_account_ids:
    - 60a683e9-09eb-434b-a922-6c9453062dbd
  position:
    x: 0
    "y": 0
nodes:
- id: auditlogs
  type: aap_job_template
  name: Gather Audit Logs
  parameters:
    diff_mode: false
    extra_vars:
      check_audit_service_issue: "${trigger.check_audit_service_issue}"
    credential_id: 5ffbf308-9bac-443b-959e-28faadbf3cc4
    integration_id: 8fa0c32c-5809-41b8-ba1e-a46d1a8e94a5
    job_template_name: pull_audit_logs
    organization_name: demo
  position:
    x: 291
    "y": 0
- id: airca
  type: agentic
  name: Get RCA and Next steps from AI
  parameters:
    prompt: |-
      'You are a technical expert specializing in Linux and Windows systems. Your task is to analyze the provided log file snippet and diagnose the cause of the system outage. Your response should follow this JSON format:
            {
              "rootCause": "",
              "escalateTo": "",
              "remediationSteps": []
            }
            Describe the root cause of the issue in the "rootCause" field, providing a concise textual explanation based on the log file snippet.
            Identify the best-suited role to address the issue in the "escalateTo" field (Developer, DBA, Server Engineer, Network Engineer, DevOps Engineer).
            List recommended steps for additional analysis or remediation in the "remediationSteps" array, providing actionable text strings that could help resolve the incident or gather more information.'

      ${auditlogs.artifacts.service_log_output}
    llm_model_id: a043c712-5301-4c31-9f8c-5e3f02a17a0e
    credential_id: 4621d59e-ceb1-4222-88e0-4ed5a9b1813b
    response_schema:
      type: object
      required:
      - rootCause
      properties:
        rootCause:
          type: string
          description: Root Cause of the issue
        escalateTo:
          type: string
          description: Team to Esclate to
        remediationSteps:
          type: string
          description: Steps to fix the issue
    tool_selection_strategy: NONE
  settings: {}
  position:
    x: 582
    "y": 0
- id: createissue
  type: aap_job_template
  name: Create new Issue
  parameters:
    credential_id: 5ffbf308-9bac-443b-959e-28faadbf3cc4
    integration_id: 8fa0c32c-5809-41b8-ba1e-a46d1a8e94a5
    organization_name: demo
    job_template_name: webapp_alert_issue
    extra_vars:
      alert_payload: "${trigger.alert_payload}"
    diff_mode: false
    use_input_variables: true
  position:
    x: 993
    "y": 0
edges:
- from: alertmanagereda
  to: auditlogs
- from: auditlogs
  to: airca
- from: airca
  to: createissue
