apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: agentic-poc-opencode
  namespace: agentic-poc
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: agentic-poc-runner
  namespace: agentic-poc
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: agentic-poc-opencode
  namespace: agentic-poc
spec:
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 3Gi
  source:
    type: Git
    git:
      uri: https://github.com/aiops-ansible-software-factory-demojam/openshift-gitops.git
      ref: 32ae9fd8fb7b7217adb85c87eb5d2e4c3cb4c05d
    contextDir: agentic-dev-poc
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: images/opencode/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: agentic-poc-opencode:git-32ae9fd8
  triggers: []
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: agentic-poc-runner
  namespace: agentic-poc
spec:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi
  source:
    type: Git
    git:
      uri: https://github.com/aiops-ansible-software-factory-demojam/openshift-gitops.git
      ref: ea1d0ef832a8509b2b82787ba8bac34610350b36
    contextDir: agentic-dev-poc
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: images/runner/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: agentic-poc-runner:git-ea1d0ef8
  triggers: []
