apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: agentic-poc-opencode
  namespace: agentic-poc
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: agentic-poc-runner
  namespace: agentic-poc
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: agentic-poc-opencode
  namespace: agentic-poc
spec:
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 3Gi
  source:
    type: Git
    git:
      uri: https://github.com/aiops-ansible-software-factory-demojam/openshift-gitops.git
      ref: f27e87de8fee52dc69994b8cc6bc031bf466ff2e
    contextDir: agentic-dev-poc
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: images/opencode/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: agentic-poc-opencode:git-f27e87de
  triggers: []
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: agentic-poc-runner
  namespace: agentic-poc
spec:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi
  source:
    type: Git
    git:
      uri: https://github.com/aiops-ansible-software-factory-demojam/openshift-gitops.git
      ref: d7557e0b628363b0c9eb7314aaded4116bba884f
    contextDir: agentic-dev-poc
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: images/runner/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: agentic-poc-runner:git-d7557e0b
  triggers: []
