apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config.yaml
  - limitrange.yaml
  - runner.yaml
  - network.yaml
  - keycloak-realm.yaml
  - image-pull-rbac.yaml
  - tls-copy-rbac.yaml
  - tls-copy-job.yaml
  - builds.yaml
