apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cnpg-ready
  namespace: cloudnative-pg
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
      - clusterserviceversions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
