apiVersion: v1
kind: Secret
metadata:
  name: automation-orchestrator-sandbox-api-token
  namespace: agent-sandbox-clients
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    kubernetes.io/service-account.name: automation-orchestrator-sandbox-api
type: kubernetes.io/service-account-token
