apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - automation-orchestrator-namespace.yaml
  - automation-orchestrator-operatorgroup.yaml
  - automation-orchestrator-subscription.yaml
  - orchestrator-pg-credentials-secret.yaml
  - temporal-pg-credentials-secret.yaml
  - automation-orchestrator-admin-password-secret.yaml
  - orchestrator-pg-cluster.yaml
  - temporal-database.yaml
  - temporal-visibility-database.yaml
  - automation-orchestrator-automationorchestrator.yaml
