apiVersion: v1
kind: Secret
metadata:
  name: orchestrator-pg-credentials
  namespace: automation-orchestrator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  database: orchestrator
  username: changeme
  password: changeme
