apiVersion: v1
kind: Secret
metadata:
  name: temporal-pg-credentials
  namespace: automation-orchestrator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  database: temporal
  username: changeme
  password: changeme
