apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: temporal-visibility
  namespace: automation-orchestrator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  cluster:
    name: orchestrator-pg
  name: temporal_visibility
  owner: changeme
  databaseReclaimPolicy: retain
